server:
  port: 9001
  
spring:  application:    name: zuul
     
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
      
zuul:
  routes:
    user:                                #定义模块
      service-id: user-provider          #用户模块服务的名称
      path: /user/**                     #url中包含user的请求可以访问服务名为user-provider的微服务
    goods:
      service-id: goods-provider
      path: /goods/**
    orders:
      service-id: orders-provider
      path: /orders/**  
                                                            